apiVersion: v1
kind: LimitRange
metadata:
  name: app-limits
spec:
  limits:
    - type: Container
      min:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 2
        memory: 2Gi
      default:
        cpu: 500m
        memory: 256Mi
      defaultRequest:
        cpu: 250m
        memory: 128Mi





# explanation

# 1️⃣ type: Container
# Limits apply per container inside each Pod.
# can be Container, Pod, PersistentVolumeClaim

# 2️⃣ min.cpu: 100m
# A container must request at least 0.1 CPU, or Kubernetes rejects it.

# 3️⃣ min.memory: 128Mi
# A container must request at least 128Mi memory, or Kubernetes rejects it.

# 4️⃣ max.cpu: 2
# A container cannot request more than 2 CPUs.

# 5️⃣ max.memory: 2Gi
# A container cannot request more than 2Gi memory.

# 6️⃣ default.cpu: 500m
# If no CPU limit is specified, Kubernetes automatically sets 500m as the limit.

# 7️⃣ default.memory: 256Mi
# If no memory limit is specified, Kubernetes automatically sets 256Mi as the limit.

# 8️⃣ defaultRequest.cpu: 250m
# If no CPU request is specified, Kubernetes automatically sets 250m as the request.

# 9️⃣ defaultRequest.memory: 128Mi
# If no memory request is specified, Kubernetes automatically sets 128Mi as the request.