apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: httpd-frontend-pod
      labels:
        type: frontend
    spec:
      containers:
      - name: httpd-frontend-container
        image: httpd:2.4-alpine